import { relations } from "drizzle-orm";
import { pgTable, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { users } from "./users";
import { cartItems } from "./cart-items";

/**
 * A shopping cart — one per logged-in user, or one per anonymous guest
 * session. Line items live on `cart_items`; this row is just the
 * container plus which owner it belongs to.
 *
 * Guest vs. authenticated is distinguished purely by `userId` being
 * `null` or not — there is no separate `isGuest` flag. A guest cart's
 * identity *is* its own `id`: the server issues an HttpOnly cookie
 * (`trends_guest_cart`, see `src/domains/cart/session.ts`) whose value is
 * this row's `id`, the same "unguessable random id as the access token"
 * pattern used by e.g. Shopify cart tokens. That id is a `uuid`
 * generated by Postgres (`defaultRandom()`), which is cryptographically
 * random — good enough entropy to serve as a bearer token, same
 * assumption this codebase already makes for password-reset tokens
 * (`password-reset-tokens.ts`), except a cart isn't a secret the way a
 * reset token is, so no additional hashing is warranted here.
 *
 * `userId` is unique (among non-null values — Postgres unique indexes
 * treat `NULL` as distinct from `NULL`, so many guest carts with
 * `userId: null` coexist fine) so "get the cart for this user" is always
 * at most one row, never an ambiguous list.
 *
 * A guest cart is merged into the user's cart at login
 * (`src/domains/cart/merge.ts`, invoked from
 * `src/domains/auth/actions.ts`'s `loginAction`/`registerAction`) and
 * then deleted — a user is never left with two carts.
 */
export const carts = pgTable(
  "carts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("carts_user_id_idx").on(table.userId)],
);

export const cartsRelations = relations(carts, ({ one, many }) => ({
  user: one(users, { fields: [carts.userId], references: [users.id] }),
  items: many(cartItems),
}));

export type Cart = typeof carts.$inferSelect;
export type NewCart = typeof carts.$inferInsert;
